# -*- coding: utf-8 -*-
"""webscraping-video3.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZ3fuF-fgWmTfJZOGmMmdK6QMWZdtEwC
"""

import requests
import re

url = "https://monicahillman.github.io/monibank/"
response = requests.get(url)
html_content = response.text

pattern = r'<(h[1-2])[^>]*>(.*?)<\/(h[1-2])>'

headings = re.findall(pattern, html_content, re.DOTALL)
for heading in headings:
  print(heading)