# -*- coding: utf-8 -*-
"""webscraping-video4.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yE8QSGQvhWhth_RaZ9AumsTr9Mine-P
"""

import requests
import re

# url da página web
url = 'https://monicahillman.github.io/monibank/'
# Realize a requisição GET para obter o conteúdo da página
response = requests.get(url)

# Verifique se a requisição foi bem-sucedida
if response.status_code == 200:
    # Conteúdo da página
    pagina = response.text

    # Padrao regex para encontrar linhas com somente a palavra "bank"
    padrao = r'\bbank\b'

    # Divida o conteúdo da página em linhas
    linhas = pagina.split('\n')

    for indice, linha in enumerate(linhas, start=1):
        if re.search(padrao, linha, re.IGNORECASE):
            print(f"Linha {indice}: {linha}")
else:
    print(f"A requisição GET para {url} falhou com o código {response.status_code}")